# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomerge < Formula
  desc "Gomerge is a tool to quickly merge several pull requests from your terminal. The intention of this tool is to simplfy, and eventually automate the merging of github pull requests. This tool should be able to run on most systems.
"
  homepage "https://github.com/Cian911/gomerge"
  version "3.2.0-rc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cian911/gomerge/releases/download/3.2.0-rc/gomerge_3.2.0-rc_Darwin_x86_64.tar.gz"
      sha256 "1f5dea395f383b597c872e70e5b5dec84448dbbcef8fc7cba75b64dcf69e6180"

      def install
        bin.install "gomerge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cian911/gomerge/releases/download/3.2.0-rc/gomerge_3.2.0-rc_Darwin_arm64.tar.gz"
      sha256 "527c423a6f1f53da4133a147177a322d9794363b6eba9210046afeff6d5c2bd3"

      def install
        bin.install "gomerge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Cian911/gomerge/releases/download/3.2.0-rc/gomerge_3.2.0-rc_Linux_armv6.tar.gz"
      sha256 "48860eab9ae55a9cc253a769355fd51f777a48df027481222312867500097e9e"

      def install
        bin.install "gomerge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Cian911/gomerge/releases/download/3.2.0-rc/gomerge_3.2.0-rc_Linux_x86_64.tar.gz"
      sha256 "65c3cdd59f4cf3abc41107e419c4eaaf842753e1ef8ab75945248135751ce31d"

      def install
        bin.install "gomerge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cian911/gomerge/releases/download/3.2.0-rc/gomerge_3.2.0-rc_Linux_arm64.tar.gz"
      sha256 "1141a4681d75795070daaa3519d1ee0e5b96cf16cbc625d182715234993d3fa6"

      def install
        bin.install "gomerge"
      end
    end
  end
end
